- LanguageExt.Core/Disposable.cs
- LanguageExt.Core/Option.cs
> LinqDisposable should derive from ILinqDisposable

- LanguageExt.Core/Disposable.cs
- LanguageExt.Core/List.cs
- LanguageExt.Core/Lst.cs
- LanguageExt.Core/MapKV.cs
- LanguageExt.Core/ObjectPool.cs
- LanguageExt.Core/Prelude_Obsolete.cs
- LanguageExt.Core/Prelude_Use.cs
- LanguageExt.Core/RWS.cs
- LanguageExt.Core/Reader.cs
- LanguageExt.Core/SetT.cs
- LanguageExt.Core/State.cs
- LanguageExt.Core/Try.cs
- LanguageExt.Core/TryOption.cs
- LanguageExt.Core/Writer.cs
- LanguageExt.Process.Redis/RedisClusterImpl.cs
- LanguageExt.Process/Actor.cs
- LanguageExt.Process/ActorInboxDual.cs
- LanguageExt.Process/ActorInboxLocal.cs
- LanguageExt.Process/ActorInboxRemote.cs
- LanguageExt.Process/Prelude_Logging.cs
- LanguageExt.Process/ProcessFlags.cs
- LanguageExt.ProcessJS/LanguageExt.ProcessJS.csproj
> Mostly clean up warnings plus one fix

- LanguageExt.Core/Either.cs
- LanguageExt.Core/EitherUnsafe.cs
- LanguageExt.Core/Exceptions.cs
- LanguageExt.Core/IMultiplicable.cs
- LanguageExt.Core/INumeric.cs
- LanguageExt.Core/LanguageExt.Core.csproj
- LanguageExt.Core/Lst.cs
- LanguageExt.Core/Option.cs
- LanguageExt.Core/OptionUnsafe.cs
- LanguageExt.Core/Prelude_Either.cs
- LanguageExt.Core/Prelude_EitherUnsafe.cs
- LanguageExt.Core/Prelude_Option.cs
- LanguageExt.Core/Prelude_OptionUnsafe.cs
- LanguageExt.Core/Prelude_Try.cs
- LanguageExt.Core/Prelude_TryOption.cs
- LanguageExt.Core/SetT.cs
- LanguageExt.Core/Try.cs
- LanguageExt.Core/TryOption.cs
- LanguageExt.Core/TypeDesc.cs
- LanguageExt.Core/UnitsOfMeasure/Accel.cs
- LanguageExt.Core/UnitsOfMeasure/Area.cs
- LanguageExt.Core/UnitsOfMeasure/Length.cs
- LanguageExt.Core/UnitsOfMeasure/Time.cs
- LanguageExt.Core/UnitsOfMeasure/TimeSq.cs
- LanguageExt.Core/UnitsOfMeasure/Velocity.cs
- LanguageExt.Core/UnitsOfMeasure/VelocitySq.cs
- LanguageExt.Tests/LanguageExt.Tests.csproj
- LanguageExt.Tests/ListMatchingTests.cs
- LanguageExt.Tests/Multiplicable.cs
Also added ~~`Bottom() helper`~~ `static readonly Bottom` so internal classes can create Bottom instance in same easy way as Left and Right helpers.
And tidied up some remaining IProductable bits to IMultiplicable, and anything similar.
> Tightened null checks in EitherT.

- LanguageExt.Core/NullableExt.cs
- LanguageExt.Core/Option.cs
- LanguageExt.Core/OptionUnsafe.cs
- LanguageExt.Core/Prelude_Either.cs
- LanguageExt.Core/Prelude_Option.cs
- LanguageExt.Core/TryOption.cs
- LanguageExt.Core/TryOutExt.cs
> Miscellaneous tweaks

- LanguageExt.Core/project.json
- LanguageExt.FSharp/project.json
- LanguageExt.Parsec/project.json
- LanguageExt.Process.FSharp/project.json
- LanguageExt.Process.Redis/project.json
- LanguageExt.Process/ActorSys/ActorContext.cs
- LanguageExt.Process/project.json
- LanguageExt.Process/project.lock.json
- LanguageExt.ProcessJS/project.json
- LanguageExt.Tests/project.json
Minor fixes to shutdown to stop infinite loop if any system opts out of the shutdown.
> Multi system

- LanguageExt.Core/Try.cs
- LanguageExt.Core/TryOption.cs
Fix build process with xbuild (v4) failed, for example, on Travis.
> Fix build with xbuild

- LanguageExt.Tests/LanguageExt.Tests.csproj
- LanguageExt.Tests/TryOption.cs
I'm creating tests as I grapple with the fundamentals. Figured i'd offer to share. Feedback welcome.
> Added a very simple test class for TryOption.

- LanguageExt.Core/List.cs
- LanguageExt.Core/Map.cs
- LanguageExt.Core/MapKV.cs
- LanguageExt.Core/Query.cs
- LanguageExt.Core/Queue.cs
- LanguageExt.Core/Stack.cs
- LanguageExt.Tests/EnumerableTTests.cs
- LanguageExt.Tests/MapTests.cs
> Fix for incorrect signature of the various choose functions

- LanguageExt.Core/TryOption.cs
> Fix typo in Iter<T>

- LanguageExt.Core/Writer.cs
> Fix typo in SelectMany<W, T, U, V>

- LanguageExt.Core/Compose.cs
- LanguageExt.Tests/CompositionTests.cs
- LanguageExt.Tests/LanguageExt.Tests.csproj
Add overloads for zero-arity and void returning functions.
Fixes #125
> Add composition overloads

- LanguageExt.Process.Redis/RedisClusterImpl.cs
ToList added to evaluate the query within Retry.
> Redis retry didn't work for QueryKeys

- LanguageExt.Core/ClassInstances/Eq/EqTryOpt.cs
- LanguageExt.Core/DataTypes/Try/Try.Extensions.cs
> Bug / typo in Try.Compare and EqTryOpt.Equals

- README.md
> docs(readme): mention IQueryable<> extensions

- LanguageExt.Core/Prelude/Prelude_Collections.cs
With two strategies for handling duplicate keys.
> Additional map constructor functions

- LanguageExt.Core/ClassInstances/Monad/MRWS.cs
- LanguageExt.Core/DataTypes/RWS/RWS.Extensions.cs
- LanguageExt.Core/DataTypes/RWS/RWS.Prelude.cs
- LanguageExt.Core/DataTypes/RWS/RWS.cs
- LanguageExt.Core/DataTypes/RWS/RWSResult.cs
- LanguageExt.Core/DataTypes/State/State.Extensions.cs
- LanguageExt.Core/DataTypes/Writer/Writer.Extensions.cs
- LanguageExt.Core/DataTypes/Writer/Writer.Prelude.cs
- LanguageExt.Core/TypeClasses/MonadRWS/MonadRWS.cs
- LanguageExt.Tests/MonadTests.cs
Hi Paul,
I finally got enough time to finish this up and review it.
I've now got a much deeper respect for your efforts in writing this library; there are quite a lot of API functions for each monad.
I'm still interested in your `MType` idea or any other way to hide the type parameter noise but that's probably a separate issue.
#244
> Reintroduce RWS Monad

- README.md
As title says, which fixes issues #336.
> removed documentation for two nonexistent TryGetValue extensions

- LanguageExt.Core/DataTypes/TryAsync/TryAsync.Extensions.cs
- LanguageExt.Core/DataTypes/TryOptionAsync/TryOptionAsync.Extensions.cs
> Memoize Tasks for Async Tries

- LanguageExt.Core/ClassInstances/Monoid/All.cs
- LanguageExt.Core/ClassInstances/Monoid/Any.cs
I found two issues, **probably** some copy/paste error.
> fix typos? (And probably should call And)

- LanguageExt.Core/DataTypes/Option-Shared/OptionData.cs
- LanguageExt.Core/DataTypes/Option/Option.cs
- LanguageExt.Core/DataTypes/OptionAsync/OptionAsync.cs
> Adding ToStringAsync and GetHashCodeAsync to OptionAsync

- LanguageExt.Core/DataTypes/Record/RecordType.cs
- LanguageExt.Tests/RecordIgnoreBaseTests.cs
> Bug fix about order of IgnoreBaseAttribute

- LanguageExt.Core/ClassInstances/Monad/MTaskFirst.cs
- LanguageExt.Core/ClassInstances/Monad/MTryFirstAsync.cs
- LanguageExt.Core/ClassInstances/Monad/MTryOptionAsync.cs
- LanguageExt.Core/ClassInstances/Monad/MTryOptionFirstAsync.cs
- LanguageExt.Core/DataTypes/Cond/CondAsync.cs
- LanguageExt.Core/DataTypes/EitherAsync/EitherAsync.cs
- LanguageExt.Core/DataTypes/OptionAsync/OptionAsync.Prelude.cs
- LanguageExt.Core/DataTypes/TryAsync/TryAsync.Extensions.cs
- LanguageExt.Core/DataTypes/TryAsync/TryAsync.Prelude.cs
- LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs
- LanguageExt.Core/DataTypes/TryOptionAsync/TryOptionAsync.Extensions.cs
- LanguageExt.Core/DataTypes/TryOptionAsync/TryOptionAsync.Prelude.cs
- LanguageExt.Core/Prelude/Prelude_Collections.cs
- LanguageExt.Tests/CondTest.cs
- LanguageExt.Tests/IssuesTests.cs
- LanguageExt.Tests/OptionAsyncTests.cs
- LanguageExt.Tests/TaskTests.cs
- Samples/TestBed/Program.cs
Replaced many occurrences of `Task.FromResult(x)` with `x.AsTask()`.
> Use more AsTask 

- LanguageExt.Core/DataTypes/UnitsOfMeasure/Accel.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Area.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Length.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Time.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/TimeSq.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Velocity.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/VelocitySq.cs
- LanguageExt.Tests/UnitsOfMeasureTests.cs
> Bug fix 419 units of measure equality

- LanguageExt.Parsec/Parsers/Prim.cs
> removed unused type parameter for parser combinator count

- LanguageExt.Core/ClassInstances/Monad/MOptionAsync.cs
- LanguageExt.Tests/OptionAsyncTests.cs
> Fix 474 m option async bi fold logic backwards

- LanguageExt.Core/DataTypes/UnitsOfMeasure/Temperature.cs
- LanguageExt.Tests/UnitsOfMeasureTests.cs
As raised in [#498](https://github.com/louthy/language-ext/issues/498).
> Temperature UoM: Add ctor args check and value retrieval

- LanguageExt.Core/DataTypes/UnitsOfMeasure/Mass.cs
- LanguageExt.Core/Prelude/Prelude_UnitsOfMeasure.cs
- LanguageExt.Tests/UnitsOfMeasureTests.cs
- README.md
As requested in issue #485 here is a pull request to add Mass as a unit of measure.
I modelled it on the other examples in there, so I think it's right. I added some unit tests, but could probably do with some more. However, I'd like some feedback before doing any more. If you're happy with what I've done, I can add more tests.
This is the first time I've done anything like this, so please be gentle with me if I've done anything wrong!
Thanks
> Unit of measure for Mass

- LanguageExt.Core/DataTypes/EitherAsync/EitherAsync.cs
- LanguageExt.Core/DataTypes/Task/Task.Extensions.cs
I think those are currently done incorrectly
> Correct null checks

- LanguageExt.Core/DataTypes/UnitsOfMeasure/Temperature.cs
- LanguageExt.Core/Exceptions.cs
- LanguageExt.Core/Prelude/Prelude_UnitsOfMeasure.cs
- LanguageExt.Parsec/Parsers/Token.cs
- LanguageExt.Tests/UnitsOfMeasureTests.cs
Should it be `Celcius` or `Celsius`? Can't find `Celcius` in the dictionary.
> Correct spelling mistakes

- LanguageExt.Core/ClassInstances/Eq/EqNewType.cs
- LanguageExt.Core/ClassInstances/Ord/OrdNewType.cs
- LanguageExt.Core/DataTypes/NewType/NewType.Predicate.Ord.cs
- LanguageExt.Core/DataTypes/NewType/NewType.Predicate.cs
- LanguageExt.Core/DataTypes/NewType/NewType.cs
- LanguageExt.Core/TypeClasses/Ord/Ord.Prelude.cs
- LanguageExt.Tests/NewTypeTests.cs
resolves louthy/language-ext #221
> Add ordering type class to NewType

- LanguageExt.Core/ClassInstances/Pred/String/Predicates.cs
- LanguageExt.Tests/PredicateTests.cs
> Add Regex match string predicate

- LanguageExt.Core/DataTypes/Record/RecordType.cs
> Optimize static loading of Record<>

- LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs
- LanguageExt.Tests/TryOption.cs
> made TryOption.Do strict

- LanguageExt.Core/DataTypes/Seq/Seq.Module.cs
- LanguageExt.Core/DataTypes/Seq/Seq.cs
- LanguageExt.Core/LanguageExt.Core.csproj
- LanguageExt.Core/Prelude/Prelude_Collections.cs
- LanguageExt.Tests/Seq.Module.Tests.cs
- LanguageExt.Tests/SeqTests.cs
- Samples/TestBed/Program.cs
- Samples/TestBed/SeqPerf.cs
* Lock free when not lazy
* Sub `20` nanosecond `Cons` and sub `30` nanosecond `Add`
> `Seq<A>` performance improvements

- LanguageExt.Core/DataTypes/UnitsOfMeasure/Length.cs
- LanguageExt.Core/Prelude/Prelude_Collections.cs
- LanguageExt.Core/Prelude/Prelude_Obsolete.cs
"Angstrom" is a very popular length measure used in semiconductor industry.
>  Add Angstrom to Length UnitOfMeasure

- LanguageExt.CodeGen/CodeGenUtil.cs
- LanguageExt.Tests/WithTests.cs
> CodeGen of With/Lens should work for properties

- LanguageExt.Core/Utility/IL.cs
- LanguageExt.Tests/RecordTypesTest.cs
> Implement better hash algorithm.

- LanguageExt.Core/Prelude/Prelude_Parse.cs
- LanguageExt.Tests/Parsing/parseTimeSpanTests.cs
- README.md
Prelude.parseTimeSpan was missing from parse-universe.
> Added Prelude.parseTimeSpan.

- LanguageExt.Core/ClassInstances/Const/Integer.cs
IMin constant was `Int32.MaxValue` and should be `Int32.MinValue`
> Fix IMin Constant

- LanguageExt.Core/ClassInstances/Const/Integer.cs
> Fix problems with Integer.cs

- LanguageExt.Core/Prelude/Prelude_Parse.cs
- LanguageExt.Tests/Parsing/AbstractParseTTests.cs
- LanguageExt.Tests/Parsing/parseEnumTests.cs
> Add Prelude.parseEnumIgnoreCase<TEnum>(string value)

- LanguageExt.CodeGen/LanguageExt.CodeGen.csproj
- LanguageExt.CodeGen/RWSGenerator.cs
- LanguageExt.Core/DataTypes/Arr/Arr.cs
- LanguageExt.Core/DataTypes/HashMap/HashMap.Eq.cs
- LanguageExt.Core/DataTypes/HashMap/HashMap.cs
- LanguageExt.Core/DataTypes/HashSet/HashSet.Eq.cs
- LanguageExt.Core/DataTypes/HashSet/HashSet.cs
- LanguageExt.Core/DataTypes/List/Lst.Predicate.cs
- LanguageExt.Core/DataTypes/List/Lst.Predicate2.cs
- LanguageExt.Core/DataTypes/List/Lst.cs
- LanguageExt.Core/DataTypes/Map/Map.cs
- LanguageExt.Core/DataTypes/OptionAsync/OptionAsync.Prelude.cs
- LanguageExt.Core/DataTypes/Seq/Seq.cs
- LanguageExt.Core/DataTypes/SeqAsync/Cases.cs
- LanguageExt.Core/DataTypes/SeqAsync/SeqAsync.cs
- LanguageExt.Core/DataTypes/Set/Set.cs
- LanguageExt.Core/DataTypes/Stack/Stck.cs
- Samples/TestBed/RobotExample.cs
- Samples/TestBed/TestBed.csproj
- Samples/TestBed/TestCodeGen.cs
* Tested the `alpha` Roslyn code-gen 
* Fixes for separators in `ToFullString` and `ToFullStringArray`
* Commented out `SeqAsync` - will re-add once I can use `IAsyncEnumerable`
> Test new codegen / various minor fixes

- LanguageExt.Core/DataTypes/Map/Map.Ord.cs
Related to #706 
@louthy, you missed two separators in commit 46a07073ffb8bd83d9ae185a9c95266d25ad5af9
> two more separator fixes

- LanguageExt.CodeGen/CodeGenUtil.cs
- LanguageExt.Core/DataTypes/EitherAsync/EitherAsync.cs
- LanguageExt.Core/DataTypes/List/Lst.Internal.cs
- LanguageExt.Core/DataTypes/OptionAsync/OptionAsync.cs
- LanguageExt.Core/DataTypes/Set/Set.cs
- LanguageExt.Core/LanguageExt.Core.csproj
- LanguageExt.Core/Prelude/Prelude_Pipe.cs
Used the wrong branch by mistake, so merging the changes from the code-gen branch.
> Fixes merge to master

- LanguageExt.Core/Prelude/Prelude.cs
- LanguageExt.Tests/SeqTests.cs
> possible fix for stackoverflow

- LanguageExt.Tests/ParsecTests.cs
Just tried to figure out things around sepBy and created unit tests for some of them.
> Some tests for sepBy/endBy parsers

- LanguageExt.Tests/SequenceStackSafetyTests.cs
> Sequence/Traverse are causing StackOverflow with Try/TryAsync

- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Validation.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/ValidationWithMonoid.cs
https://github.com/louthy/language-ext/projects/1#card-34099493
> seq traverse unit tests

- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/Validation.cs
- LanguageExt.Tests/Transformer/Traverse/SeqT/Sync/ValidationWithMonoid.cs
continuation of https://github.com/louthy/language-ext/pull/729
> make seq traverse tests consistent with other tests

- LanguageExt.Tests/Transformer/Traverse/Arr/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/Arr/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/Que/Sync/ValidationSeq.cs
https://github.com/louthy/language-ext/projects/1#card-34099474
> Que traverse tests

- LanguageExt.Tests/Transformer/Traverse/Arr/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/IEnumerable/Sync/ValidationSeq.cs
https://github.com/louthy/language-ext/projects/1#card-34099422
failing tests marked as
`[Fact(Skip = "IEnumerable comparison throws NRE")]`
> IEnumerable traverse unit tests

- README.md
Took slightly longer than I'd expect to figure out the preferred method to functionalize void and Task functions. New to functional programming so won't be offended if there is actually a better method. Included both returning the function and writing the function because many people reading the readme are also likely new to functional programming and might not be completely used to the idea of functions as values.
> #525 add explanation for making void functions return a value.

- LanguageExt.Core/DataTypes/Task/Task.Extensions.cs
- LanguageExt.Tests/TaskTests.cs
> Fix bug 758

- LanguageExt.Core/Transformer/Traverse/ValidationSeqT.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/Validation/Sync/ValidationSeq.cs
- LanguageExt.Tests/TypeClassORD.cs
Validation `Traverse` tests as mentioned in #728
> Validation traverse tests

- README.md
> Fix SeletMany Typo

- LanguageExt.Core/Transformer/Sequence/OptionAsyncT.cs
- LanguageExt.Core/Transformer/Sequence/TaskT.cs
- LanguageExt.Core/Transformer/Sequence/TryAsyncT.cs
- LanguageExt.Core/Transformer/Sequence/TryOptionAsyncT.cs
https://github.com/louthy/language-ext/issues/785
> Fix for missing windowSize usage

- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/Stck/Sync/ValidationSeq.cs
> Stck traverse tests

- LanguageExt.Tests/ExceptionMatching.cs
Adds tests for #787.
Contains renaming of existing test (cherry pick as you like).
> Add Stacktrace test for raise/rethrow

- LanguageExt.Tests/SeqTests.cs
I improved the name of a recently added test.  It now more accurately describes what is happening in the test.
> improved test name

- LanguageExt.Core/DataTypes/List/Lst.Internal.cs
- LanguageExt.Tests/ListTests.cs
> Fix index out of bounds check in LstInternal.RemoveRange

- LanguageExt.Core/DataTypes/OptionAsync/OptionAsync.cs
- LanguageExt.Core/DataTypes/OptionAsync/SomeAsyncContext.cs
- LanguageExt.Core/DataTypes/OptionAsync/SomeAsyncUnitContext.cs
- LanguageExt.Tests/OptionAsyncTests.cs
> add fluent matchers to OptionAsync

- LanguageExt.Parsec/Parsers/Char.cs
> add missing struct constraint

- LanguageExt.Core/DataTypes/OptionAsync/OptionAsync.cs
- LanguageExt.Tests/OptionAsyncTests.cs
Fixes https://github.com/louthy/language-ext/issues/831
> Do not throw exception on implicit Task<NULL> conversion

- LanguageExt.Core/Immutable Collections/BiMap/BiMap.cs
- LanguageExt.Core/Immutable Collections/HashSet/HashSet.Eq.cs
- LanguageExt.Core/Immutable Collections/HashSet/HashSet.cs
- LanguageExt.Core/Immutable Collections/Set/Set.Module.cs
- LanguageExt.Core/Immutable Collections/Set/Set.Ord.Module.cs
- LanguageExt.Core/Immutable Collections/Set/Set.Ord.cs
- LanguageExt.Core/Immutable Collections/Set/Set.cs
> fix documentation comments TryAddRange / AddOrUpdateRange

- LanguageExt.Core/Units of Measure/Velocity.cs
Fix issue https://github.com/louthy/language-ext/issues/999
> Fix incorrect creation of Velocity

- LanguageExt.Core/Effects/Eff/Extensions/Eff.Extensions.cs
Similar implementation as ``Aff.MapFail``. Addresses #1037.
> Implement Eff.MapFail

- LanguageExt.Core/Monads/Alternative Value Monads/Either/Either-Shared/EitherData.Extensions.cs
Hello team, thanks for implementing this library. I recently started using it and I can say that it's really helpful.
Added few conversion extensions for `EitherData`:
- ToEither
- ToEitherAsync
- ToEitherUnsafe
- ToFin
- ToTry
- ToTryAsync
> Add EitherDataExtensions

- LanguageExt.Core/Transformer/Traverse/EitherAsyncT..cs
- LanguageExt.Tests/TraverseTests.cs
The TraverseSerial() method no longer prematurely starts EitherAsync tasks in a lazy Seq when preallocating an array for the result.
> Fix issue where TraverseSerial() would eagerly start EitherAsync tasks
