louthy/language-ext

- LanguageExt.Core/Exceptions.cs
- LanguageExt.Core/Lst.cs
- LanguageExt.Core/SetT.cs
- LanguageExt.Core/TypeDesc.cs
- LanguageExt.Tests/Divisible.cs
- LanguageExt.Tests/LanguageExt.Tests.csproj
Added exceptions for runtime append/divide/subtract/product calls that can't be honoured.
> Lst and Set now IDivisible

- LanguageExt.Process/MessageSerialiser.cs
The strategy system doesn't work properly because of missing tags.
> Bigfix - missing tags in the Message Serializer

- LanguageExt.Core/Option.cs
Is there a reason why it is not readonly?
> Made OptionNone.Default readonly

- README.md
These lines won't compile:
```C#
string x = ifNoneUnsafe( optional, null );
string x = optional.IfNoneUnsafe(null);
```
> The call is ambiguous between the following methods or properties: 'LanguageExt.Option<string>.IfNoneUnsafe(System.Func<string>)' and 'LanguageExt.Option<string>.IfNoneUnsafe(string)'
Ofc it should specify a cast (just like in the examples a bit above).
> Fixed Option<T>.IfNoneUnsafe samples

- LanguageExt.Core/List.cs
The docs incorrectly mentions "Any in LINQ" for ForAll methods
> Documentation fixes for List/IEnumerable ForAll methods

- LanguageExt.Process/ActorSys/Deserialise.cs
This change makes the deserialization use the ActorSystemConfig.Default.JsonSerializerSettings.  Those settings are used when serializing already.  See issue #142 for more info.
> JsonSerializerSettings for Deserialize

- LanguageExt.Core/Lst.cs
- LanguageExt.Tests/ListTests.cs
Small fix for the case of nulls. 
The invariant 
> (lst1 == lst2) always gives opposite of (lst1 != lst2)
was not true, not it is true
> Bug fix for Lst<T>::operator !=

- LanguageExt.Process/ProcessName.cs
value.Length == 0 was checked again after return
> Remove unreachable code

- LanguageExt.Core/Prelude/Prelude_Parse.cs
This is my attempt at parseEnum function. There is a constraint on Enum that is must be a non-nullable value type. I added the struct constraint so that would not be an issue. The downside being that you have to use it like so, passing in the enum type
`enum breakfast { Eggs, Bacon, Toast };` `var test = parseEnum<breakfast>("Toast");`
> Added parseEnum

- LanguageExt.Tests/TryOptionApply.cs
I have made the following changes to LanguageExt.Tests.TryOptionApply.cs:
i. Renamed ApplyNoneArgsF to ApplyFailArgsF, ApplyNoneArgsF2 to ApplyFailArgsF2.
ii. Created 3 new tests: ApplyNoneArgs, ApplyNoneArgsF, ApplyNoneArgsF2.
> Some fix to LanguageExtTests.TryOptionApply.

- LanguageExt.Core/DataTypes/Result/Result.cs
- LanguageExt.Tests/ResultTests.cs
Currently, when you create a `Result<T>` with a null exception, it is considered successful. This PR fixes that.
> Fix Result<T> when created with a null exception

- LanguageExt.Core/ClassInstances/Monad/MOption.cs
- LanguageExt.Core/ClassInstances/Monad/MOptionUnsafe.cs
- LanguageExt.Tests/OptionTests.cs
The attached fix results in correct behaviour for  Option(Unsafe).BiIter(...)
call fa when some
call fb when none
A small test is included.
> Bug in biIter for Option / OptionUnsafe (fix attached)

- LanguageExt.Core/DataTypes/Try/Task.Try.Extensions.cs
- LanguageExt.Tests/Regression/Issue283.cs
Hi, 
First of all, thanks for this amazing library.
This pull request solvs some problems I've encountered related to issue #283.
Changes:
1. Added missing implementation of ToAsync that handles untyped Tasks,
2. Removed unnecessary check of Task status - awaiting on task.Value will result in exception being thrown if underlying task is faulted or cancelled, so there's no need to manually check if task has faulted,
3. Added tests for ToAsync to verify the changes
> Added missing ToAsync implementation

- LanguageExt.Core/Utility/Reflect.cs
- LanguageExt.Tests/EqualityTests.cs
> Static properties cause  Record<T>::Equals to fail

- LanguageExt.Core/DataTypes/List/Lst.Module.cs
- LanguageExt.Core/DataTypes/Seq/Seq.Module.cs
- LanguageExt.Tests/ListTests.cs
- LanguageExt.Tests/SeqTests.cs
Hello,
I have found that List.foldBackUntil() and Seq.foldBackUntil() are using foldWhile() internally.
And I have added some tests about this modification and around.
So, if this PR is acceptable level, please consider to merge this.
Regards.
> List.foldBackUntil and Seq.foldBackUntil are using foldWhile internally

- LanguageExt.Core/DataTypes/List/Lst.Extensions.cs
- LanguageExt.Core/DataTypes/List/Lst.Module.cs
- LanguageExt.Core/DataTypes/Seq/Seq.Extensions.cs
- LanguageExt.Core/DataTypes/Seq/Seq.Module.cs
- LanguageExt.Core/DataTypes/Stack/Stack.Module.cs
- LanguageExt.Tests/ListTests.cs
- LanguageExt.Tests/SeqTests.cs
Fix of #304 .
Hello,
This PR is in order to avoid ambiguous method calling and add related unit tests.
List(or Seq).foldX(foldWhile, foldBackWhile, foldUntil, foldBackUntil) causes compile time error when type S and T are same types.
A compilation time error will happen when you build following code.
```
var input = Seq(10, 20, 30, 40, 50);
var output = foldBackWhile(input, 0, (s, x) => s + x, x => x >= 40);
//The call is ambiguous between the following methods or properties:
//'Seq.foldBackWhile<S, T>(Seq<T>, S, Func<S, T, S>, Func<T, bool>)' and
//'Seq.foldBackWhile<S, T>(Seq<T>, S, Func<S, T, S>, Func<S, bool>)'
```
> Avoid ambiguous calling when S and T are same type

- LanguageExt.Core/Prelude/Prelude.cs
- LanguageExt.Tests/DefaultTests.cs
- LanguageExt.Tests/NullChecks/AbstractNullCheckTests.cs
- LanguageExt.Tests/NullChecks/IsNullExtensionTests.cs
- LanguageExt.Tests/NullChecks/isnullPreludeTests.cs
- LanguageExt.Tests/NullChecks/notnullPreludeTests.cs
- LanguageExt.Tests/NullDefaultTests.cs
I refactored the tests for `object` extension method `IsNull` and `Prelude` methods `isnull` and `notnull` so that each test includes exactly one assert while also not duplicating any code.  I added more tests, especially tests for `null` and not `null` values of a `Nullable<>` type.  Then I slightly improved the readability of the implementation of `Check<T>.IsNull`.
> improve null checking

- LanguageExt.Core/DataTypes/Option/Option.Prelude.cs
- LanguageExt.Core/Prelude/Prelude.cs
Moved the location of `public static OptionNone None` from `Prelude.cs` to `Option.Prelude.cs`.
> moved None from Prelude to Option.Prelude

- LanguageExt.Core/Prelude/Prelude_Parse.cs
- LanguageExt.Tests/Parsing/AbstractParseTPrecisionIntervalTests.cs
- LanguageExt.Tests/Parsing/AbstractParseTSignedPrecisionIntervalTests.cs
- LanguageExt.Tests/Parsing/AbstractParseTTests.cs
- LanguageExt.Tests/Parsing/AbstractParseTUnsignedPrecisionIntervalTests.cs
- LanguageExt.Tests/Parsing/parseBoolTests.cs
- LanguageExt.Tests/Parsing/parseByteTests.cs
- LanguageExt.Tests/Parsing/parseCharTests.cs
- LanguageExt.Tests/Parsing/parseDateTimeTests.cs
- LanguageExt.Tests/Parsing/parseDecimalTests.cs
- LanguageExt.Tests/Parsing/parseDoubleTests.cs
- LanguageExt.Tests/Parsing/parseEnumTests.cs
- LanguageExt.Tests/Parsing/parseFloatTests.cs
- LanguageExt.Tests/Parsing/parseGuidTests.cs
- LanguageExt.Tests/Parsing/parseIntTests.cs
- LanguageExt.Tests/Parsing/parseLongTests.cs
- LanguageExt.Tests/Parsing/parseShortTests.cs
- LanguageExt.Tests/Parsing/parseUIntTests.cs
- LanguageExt.Tests/Parsing/parseULongTests.cs
- LanguageExt.Tests/Parsing/parseUShortTests.cs
Added several tests for the family of `parseT` methods for various types `T`.  Then extracted the common logic from the implementation of those methods.
I learned two interesting things during this work.
First, the C# type system is smart enough to know that `Parse<int>(long.TryParse, value)` doesn't makes sense but not smart enough to infer that the type parameter must be `long`.
Second, `double.NaN` _cannot_ be parsed but `float.NaN` _can_.  More specifically,
```
double.TryParse(double.NaN.ToString(), out double result)
```
returns `false` but
```
float.TryParse(float.NaN.ToString(), out float result)
```
returns `true`.
> improve parse methods

- LanguageExt.Core/Extensions/ObjectExt.cs
The extension method `IsDefault` is now defined via the `Check<T>` class.
> utilzing the Check class to implement IsDefault extension method

- LanguageExt.Core/Prelude/Prelude_Parse.cs
- LanguageExt.Tests/Parsing/parseDateTimeOffsetTests.cs
DateTimeOffset is more useful than DateTime for fixed points in time because it has timezone information.
This pull request adds parseDateTimeOffset.
> adds parseDateTimeOffset and tests

- LanguageExt.Core/Prelude/Prelude_Random.cs
Both `Prelude.random` overloads claimed to be thread safe, but one of them was not, making neither thread safe.  Fixed this problem.
> make random actually thread safe

- LanguageExt.Core/DataTypes/Seq/SeqList.cs
- LanguageExt.Tests/SeqTypes/SeqListTests.cs
Fixes issues raised in #383.  In particular, I modified `Skip` and `Take` to make their outputs match that from their counterparts on `Enumerable`.
> Simplify seq list construction

- LanguageExt.Core/ClassInstances/Applicative/ApplTask.cs
- LanguageExt.Core/ClassInstances/Monad/MTaskFirst.cs
As discussed in #377, removes the dead `Task` inspection code in cases where an exception was going to be thrown anyway.  I am not completely sure about the desired behavior for the remaining cases.  I will ask about them in #377.
> Remove dead task inspection code

- LanguageExt.Core/ClassInstances/Monad/MOption.cs
- LanguageExt.Core/ClassInstances/Monad/MOptionAsync.cs
- LanguageExt.Core/DataTypes/Try/Try.Extensions.cs
- LanguageExt.Core/DataTypes/TryAsync/TryAsync.Extensions.cs
- LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs
- LanguageExt.Core/DataTypes/TryOptionAsync/TryOptionAsync.Extensions.cs
Made the first argument of these `ArgumentNullException` constructor calls the name of the null argument via a call to `nameof`.
> now passing call to namof to ArgumentNullException constructor

- LanguageExt.Core/DataTypes/TryOptionAsync/TryOptionAsync.Extensions.cs
:( found another typo (this time from [this PR](https://github.com/louthy/language-ext/pull/393))... *another sheepish grin* :)
> fixed typo from use_nameof_with_ArgumentNullException branch

- LanguageExt.Core/TypeClasses/Foldable/Foldable.cs
Fixes #405.
It is funny actually.  While making this change, I realized that there isn't a technical sense in which anything is progressing from or to left or right.  `Fold` processes elements from front to back or beginning to end while `FoldBack` (as the name implies) processes elements from back to front or end to beginning.
I suppose we think of `Fold` as processing its elements from left to right because `Fold` processes its elements in the canonical order, which for us is right to left.  We read right to left.  Anyone that draws a number line does so with the values increasing from left to right.
I think the documentation would be better if "left" and "right" were replaced by "front" and "back".  Nevertheless, I am still offering up this humble PR to fix the existing terminology. :)
> fix typo in Foldable documentation

- LanguageExt.Core/Prelude/Prelude_Parse.cs
- LanguageExt.Tests/Parsing/parseSByteTests.cs
- README.md
Addresses issue raised in #331 as well as added `parseDateTimeOffset` and `parseEnum` that were missing from the documentation.
> Improvements to the parse family of methods

- LanguageExt.Core/Prelude/Prelude_Collections.cs
Improved the documentation of `Cons` overloads by removing incorrect information (presumably added during a copy-paste) and making it more consistent.
> improved documentation of Cons overloads

- LanguageExt.Core/DataTypes/Either/Task.Either.Extensions.cs
- LanguageExt.Tests/EitherAsyncTests.cs
Repo steps:
```csharp
TryAsync( async () => {
throw new NotImplementedException();
return 1; 
})
.ToEither()
.ToAsync()
.Match(
v => Console.WriteLine($"In right - {v}"),
e => Console.WriteLine("In left")
);
```
Expected result:
`In left`
Actual result:
`In right - 0`
> Fix ToAsync for Task<Either<L,R>>

- LanguageExt.Core/DataTypes/Seq/Seq.Extensions.cs
Reduce probably was indented to work forward, ReduceBack reverse.
> fix small bug in reduce (was same order as reduceBack)

- README.md
In `Monad.Bind` method, changes the type of the `bind` parameter from `Func<B, MB>` to `Func<A, MB>`.
> Fixes typo in Bind parameter type in README.md

- LanguageExt.Core/Compose.cs
When a function has multiple type parameters, I have seen two styles for naming them in Language Ext.  One to name them like `T1`, `T2`, `T3` and the other is to name them like `A`, `B`, `C`.  I have come to really prefer the latter.
This PR changes form the first style to the second style for the functions in one file.  It also changes the parameter names (that were `a` and `b`) to avoid confusion with this new type parameter names.
> Improve type parameter names in compose extensions

- LanguageExt.Core/DataTypes/Task/Task.Extensions.cs
This should avoid the implicit ambiguous method call issue raised in #445.
Note: This seems to build fine, I was seeing some of the async tests fail intermittently even before I made any changes, so I am as sure as I can be that I didn't break anything, but it is probably worth you running the tests yourself @louthy
> Move TaskExtensions into the LanguageExt namespace

- LanguageExt.Core/ClassInstances/TBigInt.cs
- LanguageExt.Core/ClassInstances/TInt.cs
- LanguageExt.Core/ClassInstances/TLong.cs
- LanguageExt.Core/ClassInstances/TShort.cs
- LanguageExt.Tests/TypeClassBool.cs
Seems like a logic bug here. Is this fix correct? If you want I can add this for the other types (same thing with at least TInt, TLong).
> fix logic bug with biconditional in bigint

- LanguageExt.Core/DataTypes/Try/Try.Extensions.cs
- LanguageExt.Tests/UseFamilyTests.cs
#450 
The use extensions previously passed `self().Value` directly into `Prelude.use`, which resulted in a null input value to the consuming function when the initial `Try` was in a faulted state
> Updated the Use extensions to not call use on fail

- LanguageExt.Core/ClassInstances/TInt.cs
- LanguageExt.Core/ClassInstances/TLong.cs
- LanguageExt.Core/ClassInstances/TShort.cs
It looks like a recent commit put the comments out of sync with the logic for some of the BiCondition functions.
> Fixed XML comments for BiConditions

- LanguageExt.Core/DataTypes/HashMap/HashMap.Internal.cs
- LanguageExt.Core/DataTypes/HashMap/HashMap.cs
- LanguageExt.Core/DataTypes/HashSet/HashSet.Internal.cs
- LanguageExt.Core/DataTypes/Map/Map.Internal.cs
- LanguageExt.Tests/HashMapTests.cs
- LanguageExt.Tests/HashSetTests.cs
- LanguageExt.Tests/MapTests.cs
- LanguageExt.Tests/SetTests.cs
Besides some bugs (see diff) I changed two more things that aren't bugs:
1. I changed some test names and moved one test to another file, hope this is better now.
2. I modified all SetItem/Set/TrySetItem/TrySet variants so the key is replaced always. This makes it more consistent and I hope this does not have issues I didn't see. 
I don't think it is a good idea to rely on this feature in user code (key is defined as equal there), but at least LanguageExt data types have to decide which key to store. Using always the latest key makes it e.g. consistent with Remove(oldKey).Add(newKey, newValue).
I hope I found all issues.
> some tests and fixes around setitem/trysetitem for maps and sets

- LanguageExt.Core/DataTypes/List/Lst.Extensions.cs
- LanguageExt.Core/Prelude/Prelude_Collections.cs
`Seq`  had an overload of `Match` that allowed
```csharp
Seq(1, 2, 3)
.Match(
Empty: () => "",
Seq: xs => string.Join(", ", xs)
);
```
This overload was missing for IEnumerables
```csharp
// does not compile
Set(1, 2, 3)
.Match(
Empty: () => "",
More: xs => string.Join(", ", xs)
);
```
> Add missing Match overload from Seq to IEnumerables

- LanguageExt.Parsec/Parsers/Token.cs
The text was wrong for hexadecimal in parsec, looks like a copy paste issue from octal
> Fixed text for hexadecimal

- LanguageExt.Core/ClassInstances/Functor/FOption.cs
- LanguageExt.Tests/OptionTests.cs
Fixes #517.
I think this is the correct fix.  All the tests, including the newly added one, pass.
> Bug fix517 throw on option map to null

- LanguageExt.Core/ClassInstances/Foldable/FoldValidationSeq.cs
- LanguageExt.Tests/ValidationTests.cs
Small simplification and optimization in `FoldValidation.Apply`.
Also fixed the "infamous" [Y2020M11 bug](https://github.com/louthy/language-ext/commits?author=bender2k14) :P
(Otherwise, [this test](https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ValidationTests.cs#L136) would start on failing November 1, 2020.)
> Improve FoldValidation

- LanguageExt.Core/DataTypes/Try/Try.Extensions.cs
- LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs
- LanguageExt.Tests/LanguageExt.Tests.csproj
- LanguageExt.Tests/TryBottom.cs
- LanguageExt.Tests/TryOption.cs
I noticed some bugs around `Try` / `TryOption`.
The problem is that some operations (like `Sequence`/`Traverse`) might produce `Try` in `Bottom` state.
`Bottom` state means `Result`/`OptionalResult` will sometimes (`default`) have `Exception == null`.
Many methods like `Match` or `IfFail` don't check this but just pass `Exception` causing possible null errors.
(There was a small bug with order of state evaluation in TryOption, too.)
**Work in progress**: My PR fixes a few things but there is more to do as there are _many_ places to check. Before investing more time I ask for feedback:
a) What is the future of TryOption? Maybe this can be dropped (there is Try<Option>)?
b) What is the future of those Async variants. There are many overloads sometimes (but not complete).
c) Maybe change …
> Bugfix for Try / TryOption (mostly bottom state)

- LanguageExt.Core/DataTypes/Seq/Seq.cs
- LanguageExt.Tests/SerialisationTests.cs
This allows JSON deserialisation to construct a Seq as highlighted in https://github.com/louthy/language-ext/issues/579
> Made Seq constructor public to support deserialisation and added test

- README.md
Fixed broken link to section "Void isn't a real type"
> Fix link in Readme.md

- LanguageExt.Tests/ParsecTests.cs
This test fails with a NullReferenceException. I guess this is caused by static eof using static anychar being null in some execution path.
> multithreading issue with static parser definition (eof)

- LanguageExt.Tests/HashMapTests.cs
I noticed that `HashMap` is broken with certain hash values of `Key` after `RemoveRange()` operation.
> HashMap implementation is broken after RemoveRange()

- LanguageExt.Core/DataTypes/Seq/SeqStrict.cs
- LanguageExt.Tests/SeqTests.cs
In relation to #635 
Seq.Add calls CloneAdd when the Seq has already been added to. CloneAdd assumed the array needed to be expanded each time however this is not always the case and when it's not the next value was inserted in the wrong place and a value from another Seq leaked through.
> Test and fix for Seq.Add issue

- LanguageExt.Core/DataTypes/List/Lst.Extensions.cs
- LanguageExt.Core/DataTypes/List/Lst.Module.cs
- LanguageExt.Tests/ListTests.cs
This is a very minor feature request (with code + tests).
Background I often have LINQ expressions resulting in `IEnumerable<T>` with side-effects (legacy code). I need to just execute it (no return value).
This is similar to e.g. `Consume` extension function in MoreLinq but returns `Unit`.
This new `.Iter()` version could be replaced by existing `.Iter(dummy => {})` but the latter is IMHO an ugly workaround.
I don't expect this commit to be merged -- it's just a feature request.
> adds consume-only version of Iter extension

- LanguageExt.Parsec/Parsers/Prim.cs
- LanguageExt.Tests/ParsecTests.cs
I think n==0 is a valid input for `manyn0`. This change fixes it.
I copied the logic from `counti` implementation (i.e. negative values are ok, same result like 0).
Other parsers seem to have different results for out of range input values, e.g. `manyn1`:
``` 
[Fact]
public void ParseN1TimesOutOfRange()
{
Assert.Equal("", parse(asString(manyn1(digit, 0)), "1").ToEither().IfLeft("x"));
Assert.Equal("", parse(asString(manyn1(digit, 0)), "").ToEither().IfLeft("x"));
}
```
Question: Should out of range input (here: negative `n`) result in error or should it work as if minimal viable input is given or should it produce empty result? (I'm ok with "undefined" for now...)
> manyn0 parser now works correct for n==0

- LanguageExt.Core/Prelude/Prelude_Func.cs
- LanguageExt.Parsec/Parser.cs
Hi,
1. Commit: Feature PR (https://github.com/louthy/language-ext/commit/4482d003cf7eec54d7b2dc7d8b23444385f0ae39)
I think this smallest version in Prelude was just missing (exists as method).
2. Commit: Question (https://github.com/louthy/language-ext/commit/4b1abf38fc9e74e801c93cdb0465501aac613550): 
After I started to work with Parsers I often look for something like these. I guess my naming is bad and perhaps this is the wrong location for extensions like this, so ***you probably do not want to merge this as is***. Perhaps you don't want Parser to be cluttered with stuff like this (?). Anyway I'm interested in your opinion how this can be done better (in user code) with existing options or whether you like extensions like this (then guidance about naming and location would be nice).
> Compose missing variant + useful(?) extensions

- LanguageExt.Tests/MapTests.cs
As revealed through #559 and #561, `Map.Equals` should return `true` when the two maps have unequal values for the same key.  This PR adds such a test.
> Map.Equals test with different keys returns true

- LanguageExt.Tests/TraverseTests.cs
I increased timeout slightly to make the test pass more stable.
> make TraversAsync unit test pass with corecount < 6

- LanguageExt.CodeGen/CodeGenUtil.cs
- LanguageExt.Tests/UnionTests.cs
Some recent update made my serialization fail. This test shows why.
IMHO serialization should work when serialized property name has same case as code property, i.e. first letter upper case.
The serialization constructor probably should be fixed (case), but I think there is another related problem.
We can tell Newtonsoft.Json to not use ISerializable this way: 
```
new JsonSerializerSettings()
{ 
ContractResolver =  new DefaultContractResolver(){IgnoreSerializableInterface = true, IgnoreIsSpecifiedMembers = true}
}
```
This does not work either because Newtonsoft.Json can't identify the regular constructor. According to
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2229?view=vs-2019
the serialization constructor should be private (resp. protected) which will solve the issue …
> Fix union deserialisation

- LanguageExt.Core/DataTypes/Either-Shared/EItherData.cs
Noticed this when doing TryAsync(_Task in failed state_).ToEither(). The result was always in the Right state.
As a side note, I'd like to say how much I'm enjoying using this library. It's made programming in C# fun again. Keep up the good work!
> EitherData Left status from IsRight to IsLeft

- LanguageExt.Parsec/Parsers/Prim.cs
- LanguageExt.Tests/ParsecTests.cs
Fixes #699 
I arrived a this change (in the [second commit](https://github.com/louthy/language-ext/commit/4eda0278dd57a955d146db4c6d6c1e853bd5645c)) by trial-and-error with good guessing.  Or, said another way, I didn't really know what I was doing, but I found this solution that seems to work.
In particular, the parsing error message for the test case @Jmaharman gave in #699 (when trying to parse 4 digits but only given "12") is
> error at (line 1, column 3): unexpected end of stream, expecting digit
I think that is the correct error message.
The code I deleted allowed the `manyn` parser to return after processing fewer than `n` things.  I think this bug is partially due to copying and pasting the nearly identical code for the `many` and `manyn0` parsers, which do not have a minimum …
> Bug fix for #699 where manyn parses short strings

- LanguageExt.Core/DataTypes/Option/Option.cs
- LanguageExt.Tests/OptionTests.cs
see https://github.com/louthy/language-ext/issues/550
I personally would avoid this style but I see no point in having `IfSome(Action)` without having `IfNone(Action)`.
> Should solve request #550 (IfNone(Action) sideeffect)

- LanguageExt.Core/DataTypes/Try/Try.Extensions.cs
- LanguageExt.Tests/TryMonadTests.cs
- LanguageExt.Tests/TryOptionMonadTests.cs
1. `Filter` of `Try` should not execute `pred` if in faulted state.
2. `BiFilter` of `Try` should probably not be allowed to switch from faulted state back to success. This was the case when the `Fail` predicate returned `true`. `res.Value` should not be used when in faulted state and I stumbled upon getting success state with a default value. My fix would mean that `Fail` predicate can just decide whether to stay in faulted state with original exception (Fail pred => true) or to go to bottom state (Fail pred => false). I compared with `Either` but seems there is no `bifilter`. I personally wouldn't mind to remove `Try.BiFilter`.
> Fix Try.Filter / Try.BiFilter

- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/Lst/Sync/ValidationSeq.cs
Encountered some problems:
- cross product with `HashSet` fails in .NET Framework
- some weirdness with `Stck` cross product
- `Try` and `TryOption` structural equality does not work for some reason
I wanted to try fixing it but decided it's much more time-efficient if you have a look at it and I will write more tests. Plus, as an example with `Stck` not working (because of reverse iteration?), maybe it will apply for other implementations.
I added console logs for failing cases to assist in debugging.
#728
> Lst.Traverse tests

- LanguageExt.Core/TypeClasses/Ord/Ord.cs
- LanguageExt.Tests/TypeClassORD.cs
I don't know whether this is a good or bad thing.
After trying to use `Ord` with other code (e.g. LINQ OrderBy) I see some demand for conversion to types like IComparer.
> make Ord<T> usable as IComparer<T>

- LanguageExt.CodeGen/CodeGenUtil.cs
- LanguageExt.Tests/UnionTests.cs
Generated code looked like:
```csharp
class Derived
public int CompareTo(object obj) => obj is Base p ? CompareTo(p) : 1;
```
There's no downcast and so the function ended up calling itself indefinitely.
This popped up when I tried calling `Assert.Equal` on two Union instances - it uses `.CompareTo` in XUnit
`.Equals` method didn't have that problem, but I included some unit tests anyway.
> Fix Union CompareTo causing Stack Overflow

- LanguageExt.Core/Transformer/Traverse/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/Arr.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/HashSet.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/IEnumerable.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/Lst.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/Que.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/Seq.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/Set.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Collections/Stck.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/Either.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/EitherUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/Identity.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/Option.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/OptionUnsafe.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/Try.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/TryOption.cs
- LanguageExt.Tests/Transformer/Traverse/Identity/Sync/ValidationSeq.cs
As mentioned in #728 - Identity traverse tests.
Looks like `Sequence` isn't defined for `Identity<A>` so all the tests use `.Traverse(identity)`
Removed some extra generic parameters in Identity.cs which confused C# a bit.
> Identity traverse tests

- LanguageExt.CodeGen/FreeAttribute.cs
- LanguageExt.CodeGen/FreeGenerator.cs
- Samples/TestBed/TestCodeGen.cs
Resolves #757 
The idea is to have the Free code-gen handle the success path as well as the fail path by adding code-gen'd `BiMap` and BiBind implementations.
This adds a `FailNext` field in addition to the `Next` field on the non-terminal nodes of the Free.
The Free's `BiBind` and `BiMap` implementations then use this extra field.
It is up to the end-user-built `Interpreter` to make a choice between the two paths based on the outcome of the action.
While implementing it become apparent that it would be nice if the user could decorate which `Free` state represented the shortcutting-fail path so an extra `Fail` attribute was added.
With usage as follows:
```
[Free]
public interface Maybe<A>
{
[Pure] A Just(A value);
[Fail] A Nothing();
}
```
```
[Free]
public interface Try<A>
{
[Pure] A …
```
> Add BiBind to Free Code-Gen

- LanguageExt.Core/DataTypes/Validation/ValidationSeq.Extensions.cs
- LanguageExt.Core/DataTypes/Validation/ValidationSeq.Prelude.cs
Fixes #698 
I had suggested in that issue adding both the missing `Flatten` methods as well as the missing `Sequence` methods, but I feel like adding the missing `Flatten` methods is enough for now.
> added flatten functions for the seq variant of the Validation monad #698

- LanguageExt.Core/LanguageExt.Core.csproj
As mentioned in a comment for [Issue 479 (No documentation in intellisense.)](https://github.com/louthy/language-ext/issues/479#issuecomment-616479332), Commit https://github.com/louthy/language-ext/commit/01bec9f47e962b88292c30083b776be0ab860bff#diff-a2eb26bcfe1e5d97500c75f6d3698b0dL27 reintroduced the absence of XML documentation comments in the NuGet package for LanguageExt.Core.
This PR reintroduces XML documentation.
Fixes #479
> Reintroduce code documentation for NuGet

- LanguageExt.Core/DataTypes/Task/Task.Extensions.cs
**Problem**
I have some synchronous code that has to use the `HttpClient.SendAsync` method.  The code uses the Task monad.  This results in the code deadlocking (almost exactly as described in  https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).
**Improvement**
By using `ConfigureAwait(false)` throughout the `TaskExtensions` this prevents the deadlock.
**Compatibility**
The change in behaviour is whether the thread resumes on the same context, or not, after an `await`.  So if the code was used _directly_ in an ASP.NET Controller method, or in the UI thread of a Windows Forms application (or similar) which require the context, it could be a problem. But if an intermediate `await` call is made with the default `ConfigureAwait(true)` before using the TaskExtensions then …
> TaskExtensions: Add ConfigureAwait when awaiting any Task

- LanguageExt.Parsec/Parsers/Prim.cs
- LanguageExt.Tests/ParsecTests.cs
I added tests to show potential use cases. They are similar to `sepBy` but `sepBy` does not give me back separator. Maybe there are betters solutions for this. Merge, modify or just close as you like.
> add 'flatten' and 'cons' parser helpers

- LanguageExt.Core/Concurrency/Prelude.cs
Fixes #806 Method had unused argument.  I assume it was bug.
> fixing not used argument

- LanguageExt.Core/ClassInstances/Eq/EqChar.cs
- LanguageExt.Core/ClassInstances/Hashable/HashableChar.cs
- LanguageExt.Parsec/Parsers/Char.cs
- LanguageExt.Tests/ParsecTests.cs
- LanguageExt.Tests/TypeClassEQ.cs
Generic version of a parse I often use to validate e.g. filenames (case insensitive).
This variant parsers char by char and therefore needs an Eq<char> comparer. Therefore I added EqCharOrdinalIgnoreCase, too.
> add str<EQ> parser

- LanguageExt.Core/DataTypes/UnitsOfMeasure/Accel.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Area.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Length.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Mass.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Temperature.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Time.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/TimeSq.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/Velocity.cs
- LanguageExt.Core/DataTypes/UnitsOfMeasure/VelocitySq.cs
This is a suggestion.
Currently those types only implement `IComparable<T>` which is a good thing in theory because of type-safety.
But there is still code out there that uses `IComparable`.
Example: [`Assert.InRange(result, min, max)`](https://github.com/xunit/assert.xunit/blob/main/RangeAsserts.cs#L26-L30) in xunit.
I started a [discussion there](https://github.com/xunit/xunit/discussions/2176), to maybe add support for `IComparable<T>`-only types but I'm not sure what's the best way to solve this more generally. At least dotnet core itself still implements the untyped variant for e.g. [`int32`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Int32.cs).
In LanguageExt there are already a lot of types (like `Option`) that implement …
> make all UnitsOfMeasure types implement IComparable

- LanguageExt.Parsec/Parsers/Char.cs
See https://github.com/louthy/language-ext/pull/814.
This adds an explicit `LF` parser to be used instead of `newline` (which might be selected by mistake by .NET developers, especially when domesticated on Windows).
> adds `LF` parser and marks `newline` as obsolete

- LanguageExt.CodeGen/UnionGenerator.cs
Serializing a union where an abstract class is used throws exception as the generated intermediate base class is not marked as `Serializable`.  This PR makes the codegen add the missing attribute
> Add missing Serializable attribute on abstract base class in union codegen

- LanguageExt.Benchmarks/LanguageExt.Benchmarks.csproj
- Samples/RecordsNetCore/RecordsNetCore.csproj
Since no production code depends on these projects directly, the added security of upgrading to LTS might not have measurable value. However, as  a low-priority pull request, this seemed like a simple, low-risk option for a first-time contribution to an open source project.
> Upgrade benchmarks and samples projects to target .NET Core 3.1 LTS.

- LanguageExt.Core/IO/Interfaces/EnvironmentIO.cs
- LanguageExt.Core/IO/LiveIO/EnvironmentIO.cs
- LanguageExt.Core/IO/Sys/IO.Environment.cs
Add Eff support for `System.Environment`. ~~There's still some cleanup on the comments that needs to be done.~~
It was [also mentioned](https://github.com/louthy/language-ext/issues/844#issuecomment-759482845) not to return `Option`. I assume we could use `getEnvironmentVariable` as an example. In that case, it seems a little weird because it not existing isn't necessarily an error. But I'm still not clear on how to handle/deal with success, expected errors, and exceptional errors.
> Add EnvironmentIO effects

- LanguageExt.Core/Concurrency/AtomSeq/AtomSeq.cs
- LanguageExt.Tests/AtomTests.cs
AtomSeq didn't implement generic IEnumerable<A>, test added.
> fix: AtomSeq<A> now is IEnumerable<A>

- LanguageExt.Tests/AtomHashMapEqTests.cs
- LanguageExt.Tests/AtomHashMapTests.cs
- LanguageExt.Tests/RefTest.cs
Adapted from my [previous RP](https://github.com/louthy/language-ext/pull/972) and far from full code coverage.
Some things I've noticed:
* Accessing `HashMapPatch.From` for the events caused by following calls throws a `NullReferenceException`:
- `AtomHashMap<EqK, K, V>.Append` -- not implemented, uses `IEnumerable` version, while `AtomHashMap<K,V>.Append` is implemented
- `AtomHashMap<EqK, K, V>.TryAdd`
- `AtomHashMap<K, V>.TryAdd`
* `AtomHashMap<EqK, K, V>.SymmetricExcept` and `AtomHashMap<K, V>.SymmetricExcept` seem to be the same implementation as their respective `Except` function. I've tried to fix it by calling `TrieMap.SymmetricExcept` but I couldn't match the results with my expectations.
* `AtomHashMap<EqK, K, V>.Union` behaves slightly different than `AtomHashMap<K, V>.Union`. …
> Tests for Ref and AtomHashMap concerning their Change event

- LanguageExt.CodeGen/CodeGenUtil.cs
- LanguageExt.Core/Class Instances/Monad/MArray.cs
- LanguageExt.Core/Class Instances/Monad/MEnumerable.cs
- LanguageExt.Core/Immutable Collections/Arr/Arr.cs
- LanguageExt.Core/Immutable Collections/List/Lst.Module.cs
- LanguageExt.Core/Immutable Collections/Prelude_Collections.cs
- LanguageExt.Core/Immutable Collections/TrieMap/TrieMap.cs
- LanguageExt.Core/Immutable Collections/TrieSet/TrieSet.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Fin/Fin.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Some/Some.cs
- LanguageExt.Core/Type Classes/BiFoldable/BiFoldable.Prelude.cs
- LanguageExt.Core/Type Classes/BiFoldableAsync/BiFoldableAsync.Prelude.cs
- LanguageExt.Core/Type Classes/Choice/Choice.Prelude.cs
- LanguageExt.Core/Type Classes/ChoiceUnsafe/ChoiceUnsafe.Prelude.cs
- LanguageExt.Core/Type Classes/FoldableAsync/FoldableAsync.Prelude.cs
- LanguageExt.Core/Type Classes/Optional/Optional.Prelude.cs
- LanguageExt.Core/Type Classes/OptionalUnsafe/OptionalUnsafe.Prelude.cs
- LanguageExt.Core/Utility/EnumerableOptimal.cs
- LanguageExt.Parsec/PStringIO.cs
This fixes issue #997 and a few other places that I considered performance critical.
Would be interesting to actually benchmark this.
> Remove allocation overhead for empty arrays (and enumerables) (#997)

- LanguageExt.Core/Immutable Collections/Seq/SeqLazy.cs
- LanguageExt.Core/Immutable Collections/Set/Set.Ord.cs
- LanguageExt.Core/Immutable Collections/Set/Set.cs
- LanguageExt.Tests/SeqTests.cs
- LanguageExt.Tests/SetTests.cs
Two bug fixes:
* `Set.Case` returned wrong type (not `var x or var (x,xs)`)
* `SeqLazy` had broken `GetHashCode()` which could result in wrong Equality (two `Seq` could be equal with `Equals` returning false).
> Bugfixes: SeqLazy.Equals sometimes wrong, Set.Case returned wrong data/type

- LanguageExt.Core/Monads/Alternative Value Monads/Some/Some.cs
* did not compare underlying values correctly
* `Some<A>` now implements `IEquatable<Some<A>>`
Adresses issue https://github.com/louthy/language-ext/issues/1034.
> Fix Some<A>.Equals

- LanguageExt.Core/Effects/Schedule/Schedule.cs
- LanguageExt.Tests/ScheduleTest/AffTests.cs
- LanguageExt.Tests/ScheduleTest/EffTests.cs
This resolves #1065 which was discussed in #1064.
The Schedule.Run methods were capturing the S state parameter.
Have made the inline functions static to eliminated the possibility of capturing it.
Tests have been added to all Run method variants to prevent regression.
> Fixes #1065 - Schedule Run methods now do not capture free variables

- LanguageExt.Core/LanguageExt.Core.csproj
- LanguageExt.FSharp/LanguageExt.FSharp.csproj
- LanguageExt.Parsec/LanguageExt.Parsec.csproj
- LanguageExt.Rx/LanguageExt.Rx.csproj
- LanguageExt.Sys/LanguageExt.Sys.csproj
- LanguageExt.Transformers/LanguageExt.Transformers.csproj
The commit [Break out transformer extension methods into their own package](https://github.com/louthy/language-ext/commit/d6fb39a34b973708ab955ce6e6c68bdfc9d2ad51) forces everybody on non-core FW to use `Microsoft.Bcl.AsyncInterfaces` v5 or the latest v6 but with an assembly redirect.
I am updating it to v6 so we are on the latest.
> Microsoft.Bcl.AsyncInterfaces upgrade from 5.0.0 to 6.0.0

- LanguageExt.Core/Immutable Collections/HashMap/HashMap.cs
- LanguageExt.Core/Immutable Collections/Map/Map.cs
- LanguageExt.Core/Immutable Collections/TrackingHashMap/TrackingHashMap.Eq.cs
- LanguageExt.Core/Immutable Collections/TrackingHashMap/TrackingHashMap.cs
- LanguageExt.Tests/ArrayTests.cs
- LanguageExt.Tests/HashMapTests.cs
- LanguageExt.Tests/ListTests.cs
- LanguageExt.Tests/MapTests.cs
- LanguageExt.Tests/TrackingHashMapTests.cs
Updates the behaviour of itemOrNone Lenses for `Map`, `HashMap` and `TrackingHashMap` to return None if key doesn't exist in the map.
This resolves the issue raised in [#1115](https://github.com/louthy/language-ext/issues/1115)
Also includes unit tests to verify the new behaviour and the existing behaviour of `Arr` and `Lst`  itemOrNone Lenses
> Fix for #1115 Map<K,V>.itemOrNone Lens Get to return None when key does not exist

- LanguageExt.Core/Immutable Collections/Prelude_Collections.cs
- LanguageExt.Core/Type Classes/Eq/Eq.cs
- LanguageExt.Core/Type Classes/Ord/Ord.cs
- LanguageExt.Tests/TypeClassEQ.cs
- LanguageExt.Tests/TypeClassORD.cs
This is an addition to #720. I think it's less important than `IComparer` but still has some use when dealing with non-LanguageExt code (like LINQ extensions, System.Interactive ...).
I've seen that you changed #720 to avoid a record problem and I added a small assertion in that ord test to make that more explicit (avoiding that it get's changed back easily).
I renamed `Ord.ToComparable` to `Ord.ToComparer` because I think the latter is more correct to align this to *Comparable vs. *Comparer and *Equatable vs. *EqualityComparer.
> Eq.ToEqualityComparer (Ord.ToComparer)

- LanguageExt.Core/Immutable Collections/List/Lst.Module.cs
- LanguageExt.Core/Immutable Collections/Seq/Seq.Extensions.cs
- LanguageExt.Core/Immutable Collections/Seq/Seq.Module.cs
- LanguageExt.Tests/DistinctTests.cs
There is a bug in .Distinct() when a custom comparer is used. PR includes test and fix.
Bug is that default GetHashCode is used -- this is not valid with a custom (key) comparer.
First both commits only fix one occurence of the bug (there are more). Some things come to my mind (before adding more tests/fixes):
1. IMHO there should be a `Distinct<EQ, T, K>(...)` variant which I would prefer for my use case (avoiding runtime comparer).
2. Maybe avoid 'func parameter' style `Func<string,string,bool>` for helper functions like this (comparer). This would avoid hiding a gethashcode "problem" (either needs to be supplied or otherwise risks performance penalty). Should be enough to allow a variant with IEqualityComparer<T> parameter and make something like `EqCompare<T>` public to allow …
> Fix Distinct with custom comparer (hash bug)

- LanguageExt.Core/Monads/Alternative Value Monads/Either/Either/Either.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Either/EitherAsync/EitherAsync.cs
This is a minor correction of some incorrect doc strings that have tripped me up more than once. So I thought I'd contribute a fix.
> Fix incorrect docstring for two LeftToSeq implementations.

- LanguageExt.Core/Immutable Collections/Map/Map.Ord.cs
- LanguageExt.Tests/MapTests.cs
- LanguageExt.Tests/SetTests.cs
`Map<OrdK,...> + Map<OrdK,..>` returned a Map type without `OrdK`
> Fix Map<Ord,...> + Map<Ord,..> result type

- LanguageExt.Core/Effects/Pipes/Producer/Producer.cs
- LanguageExt.Tests/PipesTests.cs
The resulting producer of the function `Producer.merge` failed with an exception, when only synchronous producers were combined. The boolean variable `running` was set to false, before any items of the `queue` were yielded.
Fixes #1179
> Fix race condition when merging producers

- LanguageExt.SysX/SysX/Diag/Activity.cs
- LanguageExt.Tests/LanguageExt.Tests.csproj
- LanguageExt.Tests/SysX/Diag/ActivityTests.cs
fixes #1162
Fin does not allow null values, if the activity was null the Map on activity source would fail.
This wraps the potentially nullable activity in a wrapper that is never null.
I have also,
* added a missing operation addEvent
* added tests to all operations
> fix: value is null exception on activity span

- LanguageExt.Core/Monads/Alternative Value Monads/Option/OptionAsync/OptionAsync.Prelude.cs
This relates to #1193 - as [commented](https://github.com/louthy/language-ext/issues/1193#issuecomment-1445282575) this doesn't fix a bug in LanugageExt but just improves the API:
I enabled nullable for the whole of OptionAsync.Prelude.cs - went through all methods and changed nullability where necessary.
(I also ran all the unit tests which are still green).
> Nullability Annotations for Prelude of OptionAsync

- LanguageExt.Sys/Live/ConsoleIO.cs
- LanguageExt.Sys/MemoryConsole.cs
- LanguageExt.Sys/Sys/Console.cs
- LanguageExt.Sys/Test/ConsoleIO.cs
- LanguageExt.Sys/Traits/ConsoleIO.cs
- Samples/EffectsExamples/Menu.cs
- Samples/TestBed/PipesTest.cs
Regarding console color handling, this is the only missing function from the BCL. Thus this commit completes the console color functionalities.
> Add reset color function to console trait

- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryOption/TryOption.Extensions.cs
Relating to https://github.com/louthy/language-ext/issues/1212
Removes five duplicated extension methods on `Task<TryOption<T>>`
Extension methods with the same signatures already exist in `Task.TryOption.Extensions` on lines
https://github.com/louthy/language-ext/blob/437171250d26a5b26c516b7c0ca94ebeb67da2b6/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Try/TryOption/Task.TryOption.Extensions.cs#L215
https://github.com/louthy/language-ext/blob/437171250d26a5b26c516b7c0ca94ebeb67da2b6/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Try/TryOption/Task.TryOption.Extensions.cs#L225
https://github.com/louthy/language-ext/blob/437171250d26a5b26c516b7c0ca94ebeb67da2b6/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Try/TryOption/Task.TryOption.Extensions.cs#L236 …
> Removes duplicate extensions

- LanguageExt.Core/Immutable Collections/README.md
- README.md
This resolves the "Branch not found, redirected to default branch." warning displayed by GitHub,
> Fix links that got injured during master to main branch name change

- LanguageExt.Core/Monads/Alternative Value Monads/Try/Try/Try.Extensions.Async.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/Try/Try.Extensions.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/Try/Try.Prelude.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryAsync/TryAsync.Extensions.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryAsync/TryAsync.Prelude.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryOption/TryOption.Extensions.Async.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryOption/TryOption.Extensions.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryOption/TryOption.Prelude.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryOptionAsync/TryOptionAsync.Extensions.cs
- LanguageExt.Core/Monads/Alternative Value Monads/Try/TryOptionAsync/TryOptionAsync.Prelude.cs
Added simpler support to try and try options monads and their cooresponding async computations
Added fluent IfFail extensions for
- Try
- TryAsync
- TryOption
- TryOptionAsync
Added static function ifFail for
- Try
- TryAsync
- TryOption
- TryOptionAsync
> Added support for simpler if fail to Try monads

- LanguageExt.CodeGen/CodeGenUtil.cs
- LanguageExt.Tests/RecordCodeGenWithoutUsingLanguageExt.cs
Files containing '[Record]' classes (codegen) without `using LanguageExt;` failed to compile.
> Fix codegen record lens

- LanguageExt.Core/Common/Error.cs
- LanguageExt.Tests/ErrorTests.cs
I noticed that the `Error`s `Combine` method always returns a `ManyErrors`, even if you're concatenating a single error and an `Empty` error. This violates the identity monoid laws (assuming we want to use `==`  rather than `Error.Is` to determine Error equality, which may not be true) in addition to just _feeling_ like a bug, at least to me.
Obviously, if this was intended or is fine, please disregard!
> Identify and Fix Issue with Error Monoid Implementation

- LanguageExt.Core/Prelude/Prelude.cs
Is just that. For the C# compiler to know that the string instance is not when when using in ifs.
> Added NotNullWhenAttribute in isEmpty method
